# Book: Python Data Science Handbook
Essential Tools for Working With Data\
By **Jake VanderPlas** (2017)

## Chapter 1: IPython: Beyond Normal Python

In [2]:
L = [1, 2, 3]
L.insert?

Signature: L.insert(index, object, /)
Docstring: Insert object before index.
Type:      builtin_function_or_method

In [3]:
def square(a):
    return a**2
square??

Signature: square(a)
Docstring: <no docstring>
Source:   
def square(a):
    return a**2
File:      /tmp/ipykernel_20779/825368989.py
Type:      function

In [4]:
square(3)

9

Magic Commands

- Line magics: _prefixed by the % character_
- Cell magics: _denoted by double % (%%) prefix_

In [5]:
def func1(a, b):
    return a / b
def func2(x):
    a = x
    b = x - 1
    return func1(a, b)

## %xmode 
- xmode short for Exception mode, 
- it has three possibilities Plain, Context, and Verbose
- the default being Context

In [6]:
%xmode Plain

Exception reporting mode: Plain


In [7]:
func2(1)

ZeroDivisionError: division by zero

In [ ]:
%xmode Verbose

Exception reporting mode: Verbose


In [ ]:
func2(1)

ZeroDivisionError: division by zero

In [ ]:
%xmode Context

Exception reporting mode: Context


In [ ]:
func2(1)

ZeroDivisionError: division by zero

## Chapter 2: Introduction to NumPy

NumPy and Pandas packages are the specialized tools in Python for handling numerical arrays.

NumPy = _Numerical Python_

In [1]:
import numpy as np
np.__version__

'2.2.3'

In [ ]:
# +=, this is called Addition assignment
x = 2
x += 4
print(x)

6


### Arrays
Unlike Python lists, NumPy is constrained to arrays that all contain the same type.

In [4]:
np.array([1,4,2,5,3])

# Explicity setting the data type
np.array([1,4,2,5,3], dtype='float32')

array([1., 4., 2., 5., 3.], dtype=float32)

Unlike Python lists, NumPy arrays can be multidimensional

In [5]:
# Nested lists result in multidimensiona; arrays
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The inner lists are treated as rows of the resulting two-dimensional array.

#### Creating Arrays from Scratch

In [6]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# Create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Create an array of five(5) values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])